import { ModalProvider } from "@/components/providers/modal-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { QueryProvider } from "@/providers/query-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from "sonner";
import "./globals.css";

const font = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Adiona",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={font.className}>
            <NextTopLoader color="#10b981" showSpinner={false} />
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              storageKey="adiona-theme"
            >
              <NuqsAdapter>
                <Toaster richColors />
                <ModalProvider />
                {children}
              </NuqsAdapter>
            </ThemeProvider>
            <ReactQueryDevtools initialIsOpen={false} />
          </body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
}
